//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace muse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        public decimal MUSICID { get; set; }
        public decimal COMMENTNUMBER { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public string CONTENT { get; set; }
        public string SUBMITTIME { get; set; }
        public Nullable<decimal> LIKES { get; set; }
    
        public virtual MUSIC MUSIC { get; set; }
        public virtual MUSER MUSER { get; set; }
    }
}
