//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace muse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities5 : DbContext
    {
        public Entities5()
            : base("name=Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALBUM> ALBUM { get; set; }
        public virtual DbSet<BUYHISTORY> BUYHISTORY { get; set; }
        public virtual DbSet<COLLETION> COLLETION { get; set; }
        public virtual DbSet<COMMENTS> COMMENTS { get; set; }
        public virtual DbSet<FAULT> FAULT { get; set; }
        public virtual DbSet<FRIENDS> FRIENDS { get; set; }
        public virtual DbSet<HISTORY> HISTORY { get; set; }
        public virtual DbSet<HONOR> HONOR { get; set; }
        public virtual DbSet<MADMIN> MADMIN { get; set; }
        public virtual DbSet<MEDAL> MEDAL { get; set; }
        public virtual DbSet<MUSER> MUSER { get; set; }
        public virtual DbSet<MUSIC> MUSIC { get; set; }
        public virtual DbSet<MUSICIAN> MUSICIAN { get; set; }
        public virtual DbSet<MUSICIANWORKS> MUSICIANWORKS { get; set; }
        public virtual DbSet<MUSICTAG> MUSICTAG { get; set; }
        public virtual DbSet<SINGER> SINGER { get; set; }
        public virtual DbSet<SONGLIST> SONGLIST { get; set; }
        public virtual DbSet<SONGLISTMUSIC> SONGLISTMUSIC { get; set; }
        public virtual DbSet<TAG> TAG { get; set; }
        public virtual DbSet<USERSONGLIST> USERSONGLIST { get; set; }
        public virtual DbSet<VIP> VIP { get; set; }
    }
}
