//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace muse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSICIANWORKS
    {
        public decimal WORKS { get; set; }
        public decimal USERID { get; set; }
        public Nullable<decimal> ATTRIBUTEORDER { get; set; }
    
        public virtual MUSER MUSER { get; set; }
        public virtual MUSIC MUSIC { get; set; }
    }
}
