//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace muse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSIC()
        {
            this.BUYHISTORY = new HashSet<BUYHISTORY>();
            this.COMMENTS = new HashSet<COMMENTS>();
            this.HISTORY = new HashSet<HISTORY>();
            this.MUSICTAG = new HashSet<MUSICTAG>();
            this.SONGLISTMUSIC = new HashSet<SONGLISTMUSIC>();
            this.MUSICIANWORKS = new HashSet<MUSICIANWORKS>();
        }
    
        public decimal MUSICID { get; set; }
        public string MUSICNAME { get; set; }
        public Nullable<decimal> SINGERID { get; set; }
        public string PUBLISHER { get; set; }
        public string PUBLISHTIME { get; set; }
        public Nullable<decimal> ALBUMID { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> LIKES { get; set; }
        public Nullable<decimal> PLAYTIMES { get; set; }
        public string MUSICCOVER { get; set; }
        public string MUSICPATH { get; set; }
        public string LYRICS { get; set; }
    
        public virtual ALBUM ALBUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUYHISTORY> BUYHISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORY { get; set; }
        public virtual SINGER SINGER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSICTAG> MUSICTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SONGLISTMUSIC> SONGLISTMUSIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSICIANWORKS> MUSICIANWORKS { get; set; }
    }
}
