//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace muse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINGER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINGER()
        {
            this.ALBUM = new HashSet<ALBUM>();
            this.MUSIC = new HashSet<MUSIC>();
            this.MUSICIAN = new HashSet<MUSICIAN>();
        }
    
        public decimal SINGERID { get; set; }
        public string SINGERNAME { get; set; }
        public string SINGERIMAGE { get; set; }
        public string SINGERINTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALBUM> ALBUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSIC> MUSIC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUSICIAN> MUSICIAN { get; set; }
    }
}
